class ReligiousHoliday {
  final int month;
  final int day;
  final String name;
  final String religion;
  final String desc;
  final String detail;
  final String yi;
  final String ji;
  const ReligiousHoliday({required this.month, required this.day, required this.name, required this.religion, required this.desc, required this.detail, required this.yi, required this.ji});
}

const List<ReligiousHoliday> religiousHolidays = [
  ReligiousHoliday(month: 1, day: 1, name: '元旦', religion: '传统', desc: '公历新年第一天，全球多数国家庆祝的新年。', detail: '元旦是公历一年的第一天。在中国，元旦自1949年起成为法定假日。全球各地有不同的庆祝方式：纽约时代广场水晶球落下、伦敦泰晤士河烟花、东京增上寺敲钟108下等。元旦代表着辞旧迎新，人们制定新年计划，寄托对未来的美好期望。', yi: '祈福、许愿、家庭聚会', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 1, day: 1, name: '新年祭（正月祭）', religion: '神道教', desc: '日本最重要的节日，家庭一起参拜神社（初詣），祈求新年平安。', detail: '日本新年从1月1日持续至3日，参拜神社称为"初詣"。饮用神酒（お屠苏），吃"御节料理"。钟声敲响108下代表消除108种烦恼。', yi: '参拜神社、祈愿、家庭团聚', ji: '避免说不吉利的词语（忌词）'),
  ReligiousHoliday(month: 1, day: 6, name: '主显节', religion: '基督教', desc: '纪念耶稣向世人显现的节日，东方教会称为神显节。', detail: '主显节是基督教重要节日，西方教会纪念东方三博士朝拜婴儿耶稣，东方教会纪念耶稣受洗时圣灵降临。西班牙和拉美国家有"三王节"游行和赠礼传统。', yi: '礼拜祈祷、分享礼物、家庭团聚', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 1, day: 7, name: '东正教圣诞节', religion: '东正教', desc: '东正教按照儒略历庆祝的圣诞节。', detail: '东正教圣诞节在儒略历12月25日，对应公历1月7日。俄罗斯、塞尔维亚、乌克兰等东正教国家在这一天庆祝耶稣诞生。圣诞夜家人团聚共进"圣夜晚餐"。', yi: '参加礼拜、家庭团聚、斋期结束共享盛宴', ji: '斋期内避免肉食和娱乐'),
  ReligiousHoliday(month: 1, day: 14, name: '马凯·桑克兰提', religion: '印度教', desc: '印度教太阳节，纪念太阳进入摩羯座。', detail: '马凯·桑克兰提庆祝太阳从南半球进入北半球，标志冬天结束、丰收开始。印度各地举行盛大庆祝：北方邦圣浴、古吉拉特邦放风筝大赛、南方pongal煮饭祭典。', yi: '圣浴、放风筝、分享甜品、布施', ji: '避免食用非素食'),
  ReligiousHoliday(month: 1, day: 27, name: '国际大屠杀纪念日', religion: '犹太教', desc: '纪念纳粹大屠杀受害者的国际纪念日。', detail: '1月27日纪念1945年奥斯维辛集中营被解放。全球犹太社区举行纪念仪式，点燃蜡烛、诵读遇难者姓名，誓言"永不忘记"。', yi: '点烛纪念、诵读经文、反思历史', ji: '不宜庆祝、娱乐'),
  ReligiousHoliday(month: 2, day: 1, name: '伊玛目马赫迪诞辰', religion: '伊斯兰教', desc: '什叶派第十二伊玛目的诞辰。', detail: '纪念什叶派第十二任伊玛目穆罕默德·马赫迪的诞生。什叶派认为马赫迪处于隐遁状态，将在末日重返人间。', yi: '祈祷、诵经、分享食物', ji: '避免喧哗和不敬行为'),
  ReligiousHoliday(month: 2, day: 2, name: '圣烛节', religion: '基督教', desc: '纪念耶稣在圣殿被献与主的节日。', detail: '圣烛节纪念耶稣出生后40天被带到圣殿献给上帝。教堂在这天祝圣蜡烛，象征基督是世界之光。', yi: '点烛祈祷、参加礼拜、祝福蜡烛', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 2, day: 3, name: '节分祭', religion: '神道教', desc: '立春前一天，进行"撒豆驱鬼"仪式。', detail: '节分祭在日本各地神社举行"撒豆"仪式，喊"鬼出去，福进来"，驱除厄运招来福气。也吃与年龄同数的豆子祈求健康。', yi: '撒豆驱鬼、吃惠方卷、参拜神社', ji: '避免说不吉利的话'),
  ReligiousHoliday(month: 2, day: 10, name: '春节', religion: '传统', desc: '中国农历新年，是最重要的传统节日。', detail: '春节是中国及东亚地区最重要的传统节日。习俗包括除夕夜全家团聚吃年夜饭、守岁迎新；正月初一拜年、发红包；舞龙舞狮、放鞭炮。2024年起春节被列为联合国假日。', yi: '团圆、拜年、祭祖、发红包、祈福', ji: '忌说不吉利的话、忌打破器物、忌扫地倒垃圾'),
  ReligiousHoliday(month: 2, day: 14, name: '圣灰星期三', religion: '基督教', desc: '大斋期的开始，信徒会在额头上涂抹灰烬。', detail: '圣灰星期三是大斋期的第一天。牧师用灰烬在信徒额头上画十字，说"你本是尘土，仍要归于尘土"。大斋期持续40天，信徒通过禁食、祈祷和施舍预备心灵。', yi: '忏悔、祈祷、禁食、施舍', ji: '避免宴乐、过度饮食'),
  ReligiousHoliday(month: 2, day: 15, name: '涅槃节', religion: '佛教', desc: '纪念佛陀在拘尸那迦入灭（涅槃）的日子。', detail: '涅槃节是大乘佛教纪念释迦牟尼佛入灭的日子。佛教徒在这天诵念《大般涅槃经》，反思无常与生死，部分寺庙举行供灯和禅修。', yi: '诵经、供灯、禅修、反思无常', ji: '避免杀生、喧哗娱乐'),
  ReligiousHoliday(month: 2, day: 26, name: '湿婆之夜', religion: '印度教', desc: '纪念湿婆神的盛大节日，信徒彻夜祈祷。', detail: '湿婆之夜是印度教最盛大的节日之一。信徒整夜不眠，在湿婆神庙中诵经祈祷、献上牛奶和Bel叶，禁食冥想。', yi: '禁食、彻夜祈祷、献供、冥想', ji: '避免睡眠、进食、娱乐'),
  ReligiousHoliday(month: 3, day: 8, name: '胡里节', religion: '印度教', desc: '印度教色彩节，象征善胜恶、春天来临。', detail: '胡里节又称"色彩节"，第一天点燃篝火纪念善胜恶，第二天人们互相泼洒彩色粉末和水，载歌载舞，共享甜食。', yi: '泼洒彩色粉末、歌舞、分享甜食', ji: '忌对不愿参与者强行泼洒'),
  ReligiousHoliday(month: 3, day: 10, name: '开斋节', religion: '伊斯兰教', desc: '斋月结束后的庆祝节日，标志着斋戒的完成。', detail: '开斋节是伊斯兰教两大节日之一。穆斯林清晨沐浴更衣，前往清真寺举行集体礼拜，缴纳"开斋捐"，之后家人团聚，互赠礼物，享用盛宴。', yi: '集体礼拜、施舍开斋捐、家庭团聚、互赠礼物', ji: '斋月期间白天禁止饮食'),
  ReligiousHoliday(month: 3, day: 17, name: '圣帕特里克节', religion: '基督教', desc: '纪念爱尔兰守护圣人圣帕特里克的节日。', detail: '圣帕特里克节以绿色为主题：穿绿衣、戴绿帽、游行庆典。都柏林、纽约、芝加哥等城市都举行盛大游行。', yi: '参加游行、穿绿色服饰、祈祷', ji: '避免过度饮酒'),
  ReligiousHoliday(month: 3, day: 21, name: '诺鲁孜节', religion: '琐罗亚斯德教', desc: '波斯新年，也是琐罗亚斯德教的重要节日。', detail: '诺鲁孜节在3月21日春分，有3000多年历史。节前举行"跳火节"，节日当天摆设"Haft-sin"桌，象征新生和繁荣。', yi: '跳火净化、摆Haft-sin桌、访亲问友、分享食物', ji: '避免不洁之物接触火'),
  ReligiousHoliday(month: 3, day: 21, name: '纳夫鲁兹节', religion: '巴哈伊教', desc: '巴哈伊教新年，标志斋月结束。', detail: '纳夫鲁兹节是巴哈伊教新年，在春分日，标志19天斋月结束。信徒举行祈祷与聚会。', yi: '祈祷聚会、庆祝新年、结束斋戒', ji: '斋月期间白天禁食'),
  ReligiousHoliday(month: 3, day: 29, name: '耶稣受难日', religion: '基督教', desc: '纪念耶稣基督被钉十字架受难的节日。', detail: '耶稣受难日在复活节前的星期五。教堂举行庄严的受难日礼拜，诵读受难史，有些教会举行"十架苦路"巡游。', yi: '参加受难日礼拜、祈祷、忏悔、禁食', ji: '避免宴乐庆祝、娱乐活动'),
  ReligiousHoliday(month: 3, day: 31, name: '复活节', religion: '基督教', desc: '纪念耶稣基督复活的重要节日。', detail: '复活节是基督教最重要的节日，庆祝耶稣复活。全球基督徒举行盛大的复活节礼拜，点燃复活蜡烛。复活节彩蛋象征新生命。', yi: '参加复活节礼拜、庆祝、分享彩蛋、家庭团聚', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 4, day: 2, name: '拉玛·纳瓦米', religion: '印度教', desc: '纪念印度教神祇罗摩诞辰的节日。', detail: '拉玛·纳瓦米纪念毗湿奴第七化身罗摩的诞生。信徒诵读《罗摩衍那》、唱诵赞歌、禁食祈祷。', yi: '诵读史诗、禁食祈祷、圣浴', ji: '避免进食至午后'),
  ReligiousHoliday(month: 4, day: 9, name: '大雄诞辰', religion: '耆那教', desc: '纪念耆那教创始人摩诃毗罗诞辰的节日。', detail: '大雄诞辰是耆那教最重要的节日。耆那教徒举行游行，诵读经典，施舍穷人，寺庙中举行沐浴圣像的仪式。', yi: '游行、诵经、施舍、沐浴圣像', ji: '严格禁止杀生、避免食用根茎类蔬菜'),
  ReligiousHoliday(month: 4, day: 13, name: '宋干节', religion: '佛教', desc: '泰国、老挝等东南亚国家的新年，也是佛教重要节日。', detail: '宋干节人们互相泼水，象征洗去罪孽。信徒到寺庙礼佛、为佛像泼水祈福、堆沙塔、放生。', yi: '泼水祈福、礼佛、放生、堆沙塔', ji: '避免不敬佛教圣地'),
  ReligiousHoliday(month: 4, day: 13, name: '拜萨哈节', religion: '锡克教', desc: '纪念1699年第十祖建立卡尔萨组织。', detail: '拜萨哈节纪念第十祖建立卡尔萨组织，也是旁遮普丰收节。举行集体洗礼、武术表演、游行和庆典。', yi: '参加游行、武术表演、免费供餐', ji: '禁止饮酒吸烟'),
  ReligiousHoliday(month: 4, day: 17, name: '逾越节', religion: '犹太教', desc: '纪念以色列人出埃及的节日，持续七天或八天。', detail: '逾越节是犹太教最重要的节日之一。逾越节家宴（Seder）是核心仪式：诵读出埃及故事，食用象征性食物——苦菜象征奴役、无酵饼象征匆忙离开。', yi: '举行家宴、诵读出埃及故事、食用无酵饼', ji: '禁止食用发酵食品、禁食面筋类食物'),
  ReligiousHoliday(month: 4, day: 21, name: '里兹万节', religion: '巴哈伊教', desc: '纪念巴哈欧拉宣布使命的最伟大节日。', detail: '里兹万节是巴哈伊教最伟大的节日，纪念1863年巴哈欧拉宣布使命。第一天、第九天、第十二天为圣日，需停止工作。', yi: '祈祷、聚会、停止工作', ji: '圣日禁止工作'),
  ReligiousHoliday(month: 4, day: 23, name: '圣乔治节', religion: '基督教', desc: '纪念英格兰守护圣人圣乔治的节日。', detail: '圣乔治节在4月23日。在英格兰人们佩戴红玫瑰、升起圣乔治旗。这天也是世界读书日。', yi: '佩戴红玫瑰、参加礼拜、赠书', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 5, day: 1, name: '卫塞节', religion: '佛教', desc: '纪念佛陀诞生、成道、涅槃的节日。', detail: '卫塞节是南传佛教最重要的节日，将佛陀诞生、成道和涅槃三大事件合为一天纪念。信徒到寺庙供灯、献花、诵经、浴佛。', yi: '供灯、献花、诵经、浴佛、布施', ji: '避免杀生、饮酒、娱乐'),
  ReligiousHoliday(month: 5, day: 9, name: '耶稣升天节', religion: '基督教', desc: '纪念耶稣基督升天的节日。', detail: '耶稣升天节在复活节后第40天，纪念耶稣在门徒面前升天。升天节后十天为"祈祷十天"，预备圣灵降临。', yi: '参加礼拜、祈祷', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 5, day: 19, name: '五旬节', religion: '基督教', desc: '圣灵降临节，纪念圣灵降临在使徒身上。', detail: '五旬节纪念圣灵降临在使徒身上，教会由此诞生，被称为"教会的生日"。传统上教堂用红色装饰。', yi: '参加礼拜、祈祷感恩、穿红色服饰', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 5, day: 23, name: '巴孛宣言日', religion: '巴哈伊教', desc: '纪念1844年巴孛宣布使命。', detail: '巴孛宣言日纪念1844年巴孛在设拉子向第一位信徒宣布使命，这是巴哈伊信仰的起点。', yi: '祈祷、聚会、纪念', ji: '此日为圣日，停止工作'),
  ReligiousHoliday(month: 5, day: 26, name: '佛陀诞辰', religion: '佛教', desc: '北传佛教纪念释迦牟尼佛诞生的日子。', detail: '佛陀诞辰在农历四月初八。"浴佛节"是最核心的仪式：信众以香汤沐浴佛诞像，象征洗涤自身烦恼。', yi: '浴佛、诵经、供灯、放生、行善', ji: '避免杀生、饮酒、荤食'),
  ReligiousHoliday(month: 6, day: 5, name: '萨瓦特里普贾', religion: '印度教', desc: '印度教已婚妇女为丈夫祈福的节日。', detail: '已婚妇女为丈夫健康长寿守斋祈祷，源于萨瓦特里凭借信仰使死神归还丈夫生命的故事。', yi: '禁食祈祷、系红线、互赠礼物', ji: '已婚妇女当日禁食'),
  ReligiousHoliday(month: 6, day: 7, name: '古尔邦节', religion: '伊斯兰教', desc: '宰牲节，纪念易卜拉欣愿意献祭儿子的忠诚。', detail: '古尔邦节是伊斯兰教最重要的节日。穆斯林清晨礼拜后宰牲，肉分三份：一份自用、一份赠亲友、一份施穷人。', yi: '集体礼拜、宰牲献祭、施舍穷人、访亲问友', ji: '禁止食用未按清真方式宰杀的肉'),
  ReligiousHoliday(month: 6, day: 17, name: '伊斯兰新年', religion: '伊斯兰教', desc: '希吉来历新年的第一天。', detail: '伊斯兰新年纪念公元622年先知穆罕默德迁徙。这是一个安静、反思的日子。', yi: '反思、祈祷、静修', ji: '不宜庆祝宴乐'),
  ReligiousHoliday(month: 6, day: 21, name: '夏至', religion: '传统', desc: '北半球白昼最长的一天，许多文化都有庆祝活动。', detail: '夏至北半球白昼最长。英国巨石阵观赏夏至日出；北欧庆祝仲夏节；中国有"冬至饺子夏至面"的传统。', yi: '祭祀、祈福、吃面', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 6, day: 21, name: '毛利新年', religion: '毛利宗教', desc: '昴宿星团升起标志新年开始。', detail: '毛利新年（Matariki）在6-7月昴宿星团升起时，2022年起成为新西兰法定公共假期。象征缅怀逝者、庆祝丰收、规划未来。', yi: '燃火祭祀、供奉食物、歌舞', ji: '避免在仪式中喧哗'),
  ReligiousHoliday(month: 7, day: 7, name: '七夕', religion: '传统', desc: '中国传统情人节，纪念牛郎织女相会。', detail: '七夕节源于牛郎织女传说。古代女子"乞巧"，向织女祈求灵巧技艺和美好姻缘。2006年被列入非遗名录。', yi: '乞巧、赏星、祈愿姻缘', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 7, day: 9, name: '巴孛殉教日', religion: '巴哈伊教', desc: '纪念1850年巴孛在大不里士被处决。', detail: '巴孛殉教日纪念1850年巴孛被处决。巴哈伊教信徒在中午停止工作，诵读巴孛的经文。', yi: '祈祷、诵读经文、停止工作', ji: '此日为圣日，停止工作'),
  ReligiousHoliday(month: 7, day: 17, name: '阿舒拉节', religion: '伊斯兰教', desc: '什叶派纪念侯赛因殉难的重要节日。', detail: '阿舒拉节是什叶派最悲痛的纪念日，纪念侯赛因在卡尔巴拉殉难。什叶派穿黑衣、捶胸痛哭。逊尼派则纪念摩西渡过红海。', yi: '祈祷、反思、斋戒', ji: '什叶派不宜庆祝宴乐'),
  ReligiousHoliday(month: 7, day: 21, name: '甘露节', religion: '锡克教', desc: '锡克教庆祝胡里节后一天的武士节日。', detail: '甘露节展示锡克教武士的军事传统和勇武精神。信徒举行武术表演、骑术比赛、诗歌朗诵和集体祈祷。', yi: '武术表演、祈祷、免费供餐', ji: '禁止饮酒吸烟'),
  ReligiousHoliday(month: 7, day: 24, name: '先驱者日', religion: '摩门教', desc: '纪念杨百翰率首批先驱进入盐湖谷。', detail: '先驱者日为犹他州年度最大庆典，包含游行、牛仔竞技及复古活动。', yi: '参加庆典、游行、历史纪念', ji: '摩门教信徒周日避免购物娱乐'),
  ReligiousHoliday(month: 8, day: 6, name: '显荣节', religion: '东正教', desc: '纪念耶稣在大博尔山显圣容。', detail: '显荣节纪念耶稣在大博尔山在门徒面前显出神圣光辉。东正教在这天祝福水果。', yi: '参加礼拜、祝福水果、祈祷', ji: '斋期内遵守斋规'),
  ReligiousHoliday(month: 8, day: 15, name: '圣母升天节', religion: '天主教', desc: '纪念圣母玛利亚灵魂与肉身一同升天的节日。', detail: '圣母升天节是天主教和东正教的重要节日。在法国、意大利、西班牙等许多天主教国家是公共假日。教堂举行隆重弥撒。', yi: '参加弥撒、手持鲜花蜡烛游行', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 8, day: 19, name: '盂兰盆节', religion: '佛教', desc: '佛教重要节日，又称中元节，祭祀祖先。', detail: '盂兰盆节源于目连救母故事。中国"中元节"、日本"お盆"、韩国"百中节"都源于此。日本盂兰盆舞和放河灯是著名节庆活动。', yi: '诵经、供僧、祭祖、放河灯', ji: '避免夜间外出（民间信仰）、杀生'),
  ReligiousHoliday(month: 8, day: 26, name: '克里希纳诞辰', religion: '印度教', desc: '纪念印度教神祇克里希纳诞辰的节日。', detail: '克里希纳诞辰纪念毗湿奴第八化身克里希纳的诞生。信徒守夜至午夜诵经，寺庙举行摇篮礼。', yi: '守夜、诵经、献供、禁食至午夜', ji: '午夜前不宜进食'),
  ReligiousHoliday(month: 8, day: 29, name: '巴哈欧拉升天日', religion: '巴哈伊教', desc: '纪念巴哈欧拉于1892年逝世。', detail: '巴哈欧拉升天日纪念巴哈欧拉逝世。信徒在清晨举行特别祈祷会。', yi: '清晨祈祷、诵读经文', ji: '此日为圣日，停止工作'),
  ReligiousHoliday(month: 9, day: 7, name: '象头神节', religion: '印度教', desc: '纪念象头神伽内什的节日。', detail: '象头神节是印度教最盛大的公众节日之一。节日持续1-11天，最后一天举行盛大的浸像仪式。', yi: '安放神像、献花供果、诵经、游行', ji: '不宜在此期间开始新事业（部分传统）'),
  ReligiousHoliday(month: 9, day: 9, name: '重阳节', religion: '道教', desc: '斗姆元君与真武大帝圣诞，也是登高敬老的日子。', detail: '重阳节在农历九月初九。道教视为斗姆元君与真武大帝圣诞。也是中国传统节日，登高赏秋，现为老年节。', yi: '登高、敬老、饮菊花酒、佩茱萸', ji: '避免说不敬老的话'),
  ReligiousHoliday(month: 9, day: 14, name: '十字架举荣节', religion: '东正教', desc: '纪念十字架被发现与高举。', detail: '十字架举荣节纪念海伦娜发现真十字架。东正教将十字架高举于会众中央，信徒敬礼叩拜。', yi: '参加礼拜、敬礼十字架', ji: '斋期内遵守斋规'),
  ReligiousHoliday(month: 9, day: 15, name: '赎罪日', religion: '犹太教', desc: '犹太教最神圣的日子，进行禁食和忏悔。', detail: '赎罪日是犹太教最神圣最庄严的日子。犹太人完全禁食25小时，在会堂中祈祷忏悔。以色列在这天全国停摆。', yi: '禁食、祈祷、忏悔、施舍', ji: '严禁饮食、洗浴、穿皮鞋、行房、工作'),
  ReligiousHoliday(month: 9, day: 20, name: '住棚节', religion: '犹太教', desc: '纪念以色列人在旷野住棚的七天节日。', detail: '住棚节持续七天。犹太人建造"苏卡"（临时棚屋），全家人在苏卡中吃饭，手持"四种植物"游行。', yi: '建造苏卡、在苏卡中用餐、手持四种植物游行', ji: '不可在苏卡外用餐（节日期间）'),
  ReligiousHoliday(month: 9, day: 26, name: '十胜节', religion: '印度教', desc: '纪念罗摩战胜魔王罗波那的节日。', detail: '十胜节纪念罗摩击败魔王罗波那，象征正义战胜邪恶。焚烧巨大魔王像，象征恶的毁灭。', yi: '焚烧魔王像、启动新事业、祈祷', ji: '避免不敬神灵'),
  ReligiousHoliday(month: 9, day: 29, name: '米迦勒节', religion: '基督教', desc: '纪念天使长米迦勒和众天使的节日。', detail: '米迦勒节纪念天使长米迦勒和众天使。英国传统上在这天吃鹅肉。许多大学和法律年度从米迦勒节开始。', yi: '参加礼拜、感恩、团聚', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 10, day: 3, name: '中秋节', religion: '传统', desc: '中国传统节日，家人团聚赏月吃月饼。', detail: '中秋节是中国仅次于春节的第二大传统节日，有2000多年历史。以月圆象征团圆，家人围坐赏月、吃月饼。2006年列入非遗名录。', yi: '赏月、团聚、吃月饼、祭月', ji: '忌对月不敬、忌独自赏月（民间说法）'),
  ReligiousHoliday(month: 10, day: 3, name: '开天节', religion: '天道教', desc: '纪念檀君开国，天道教与民族主义传统紧密相连。', detail: '开天节纪念檀君建立古朝鲜。韩国在10月3日举行纪念活动。', yi: '参加纪念仪式、祈祷', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 10, day: 12, name: '排灯节', religion: '印度教', desc: '印度教光明节，象征光明战胜黑暗。', detail: '排灯节是印度教最盛大的节日。核心仪式是点燃油灯和蜡烛，象征光明驱散黑暗。人们打扫房屋、穿新衣、放鞭炮、交换甜食。', yi: '点灯、穿新衣、分享甜食、拜访亲友', ji: '避免在黑暗中不点灯'),
  ReligiousHoliday(month: 10, day: 20, name: '古鲁那纳克诞辰', religion: '锡克教', desc: '纪念锡克教创始人古鲁那纳克的诞辰。', detail: '古鲁那纳克诞辰纪念锡克教创始人诞生。节日持续48小时不间断诵读经典，当天凌晨举行晨祷，之后免费提供圣餐。', yi: '不间断诵读经典、晨祷、免费供餐、游行', ji: '禁止饮酒吸烟'),
  ReligiousHoliday(month: 10, day: 31, name: '万圣节', religion: '基督教', desc: '诸圣节前夕，纪念所有圣徒的节日。', detail: '万圣节是诸圣节的前夜，起源于凯尔特人的萨温节。"Trick or Treat"习俗始于美国。如今万圣节已成为全球性娱乐节日。', yi: '纪念先人、参加教会活动', ji: '避免过度恐惧或不当装扮'),
  ReligiousHoliday(month: 11, day: 1, name: '诸圣节', religion: '基督教', desc: '纪念所有圣徒和殉道者的节日。', detail: '诸圣节纪念所有已封圣的圣徒和殉道者。在天主教国家11月1日是公共假日，人们去墓地为已故亲人献花点蜡烛。', yi: '参加弥撒、为亡者祈祷、扫墓献花', ji: '不宜庆祝宴乐'),
  ReligiousHoliday(month: 11, day: 2, name: '万灵节', religion: '基督教', desc: '纪念所有亡者的节日。', detail: '万灵节是天主教纪念所有已亡信众的节日。信徒为亡者祈祷、献弥撒、扫墓点烛。墨西哥将此日合并为"亡灵节"。', yi: '为亡者祈祷、点烛、扫墓', ji: '不宜庆祝宴乐'),
  ReligiousHoliday(month: 11, day: 12, name: '光明节', religion: '犹太教', desc: '纪念马加比起义胜利和圣殿灯油奇迹的八天节日。', detail: '光明节持续八天，纪念马加比起义收复圣殿的奇迹。核心仪式是点燃九灯台：每晚增加一盏灯。家庭习俗包括玩陀螺、吃油炸食品、赠送礼物。', yi: '点灯、祈祷、吃油炸食品、玩陀螺、赠礼', ji: '光明节期间灯台不可熄灭'),
  ReligiousHoliday(month: 11, day: 15, name: '佛成道日', religion: '佛教', desc: '纪念佛陀在菩提树下证悟成佛的日子。', detail: '佛成道日在农历十二月初八，纪念佛陀悟道成佛。中国寺庙在这天煮"腊八粥"供众，已融入民间成为"腊八节"。', yi: '煮腊八粥、诵经、供灯、禅修', ji: '避免杀生、荤食'),
  ReligiousHoliday(month: 11, day: 24, name: '锡克教殉道节', religion: '锡克教', desc: '纪念第九任古鲁得格·巴哈杜尔殉道。', detail: '锡克教殉道节纪念第九任古鲁为保护宗教自由而殉道。锡克教徒朝圣，举行祈祷和诵经。', yi: '朝圣、祈祷、诵经', ji: '禁止饮酒吸烟'),
  ReligiousHoliday(month: 11, day: 26, name: '圣约日', religion: '巴哈伊教', desc: '纪念阿博都巴哈被宣布为圣约的中心。', detail: '圣约日纪念阿博都巴哈被正式宣布为巴哈欧拉圣约的中心与诠释者。', yi: '祈祷、聚会、纪念', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 12, day: 8, name: '圣母无染原罪节', religion: '天主教', desc: '纪念圣母玛利亚受孕时未受原罪玷污的节日。', detail: '圣母无染原罪节在12月8日，是天主教信条。在许多天主教国家是公共假日，也是圣诞季正式开始的日子。', yi: '参加弥撒、开始圣诞装饰', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 12, day: 12, name: '瓜达卢佩圣母节', religion: '天主教', desc: '纪念瓜达卢佩圣母显现的节日。', detail: '瓜达卢佩圣母节纪念1531年圣母在墨西哥显现。数百万墨西哥人前往朝圣。瓜达卢佩圣母是墨西哥和全美洲的主保圣人。', yi: '朝圣、祈祷、唱颂歌', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 12, day: 21, name: '冬至', religion: '传统', desc: '北半球白昼最短的一天，中国有"冬至大如年"之说。', detail: '冬至中国自古重视，有"冬至大如年"的说法。北方吃饺子、南方吃汤圆。古代是天子祭天的大日子。', yi: '祭祖、吃饺子/汤圆、团圆', ji: '民间忌冬至不出门、忌晚归'),
  ReligiousHoliday(month: 12, day: 21, name: '密特拉节', religion: '琐罗亚斯德教', desc: '纪念光明战胜黑暗的转折点。', detail: '密特拉节在冬至，纪念光明战胜黑暗的转折点，波斯古密特拉信仰的遗存。', yi: '点燃圣火、祈祷、庆祝光明重生', ji: '禁止熄灭圣火'),
  ReligiousHoliday(month: 12, day: 23, name: '约瑟·斯密诞辰', religion: '摩门教', desc: '纪念摩门教创始人约瑟·斯密诞辰。', detail: '纪念摩门教创始人约瑟·斯密诞辰。各分会举办历史讲座及灵修会。', yi: '参加灵修会、历史讲座', ji: '摩门教信徒禁止饮酒咖啡'),
  ReligiousHoliday(month: 12, day: 25, name: '圣诞节', religion: '基督教', desc: '纪念耶稣基督诞生的重要节日。', detail: '圣诞节是基督教最广为人知的节日，纪念耶稣诞生。习俗包括圣诞树、圣诞老人、唱颂歌、交换礼物等。', yi: '参加圣诞礼拜、家庭团聚、交换礼物、唱颂歌', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 12, day: 26, name: '节礼日', religion: '基督教', desc: '圣诞节后的第一天，传统上向穷人施舍礼物。', detail: '节礼日传统上向穷人施舍礼物。英联邦国家定为公共假日。如今已成为全球最大购物折扣日之一。', yi: '施舍、赠礼、购物', ji: '无特殊禁忌'),
  ReligiousHoliday(month: 12, day: 31, name: '法瓦蒂干节', religion: '琐罗亚斯德教', desc: '纪念亡魂回归探访生者。', detail: '法瓦蒂干节在12月31日至1月4日，纪念亡魂回归。信徒在火庙祈祷，施舍食物。', yi: '祈祷、施舍、纪念亡者', ji: '禁止在火前谈论污秽之事'),
];
