name: Build & Deploy Flutter Web

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href="/"

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: cfk_8htOHZ0dmYVg0a2Vm4ArBD5S9NWaHDKYOa5IAp0u309bfa99
          CLOUDFLARE_ACCOUNT_ID: e3cfcf3046c4b621689891ffe3c9ad49
        run: wrangler pages deploy build/web --project-name=openfaith --branch=main
